### PR TITLE
Fix blog name

### PR DESCRIPTION
**Pull request by szepeviktor**
Two less typos in that line.

... wait! Three??? Byte vs. Bite 👈🏻

### CODE REVIEW

**Comment by adamlaki** [comment]
Not my proudest. Thank you!

**Comment by szepeviktor** [comment]
> ... wait! Three??? Byte vs. Bite 👈🏻

What about this one?

**Comment by adamlaki** [comment]
Bite-sized is the correct one: https://dictionary.cambridge.org/dictionary/english/bite-sized#google_vignette

**Comment by szepeviktor** [comment]
Okay, I let **you** correct "Byte-Sized".

**Comment by adamlaki** [comment]
Done, thank you!

**Pull request merged**
